on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update_calanders:
    environment: main
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: bun install

      - name: Update Calanders
        env:
          CAL_LINK: ${{ secrets.CAL_LINK }}
        run: bash ./scripts/download.sh

      - run: bun run index.ts
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
